// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaBot.Models;

#nullable disable

namespace PizzaBot.Migrations
{
    [DbContext(typeof(PizzaContext))]
    partial class PizzaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PizzaBot.Models.PizzaRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("priority")
                        .HasColumnType("float");

                    b.Property<int>("reqPiecesMeat")
                        .HasColumnType("int");

                    b.Property<int>("reqPiecesVegan")
                        .HasColumnType("int");

                    b.Property<int>("reqPiecesVegetarian")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("PizzaBot.Models.PizzaResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("hasPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("penaltyMeatVeggi")
                        .HasColumnType("float");

                    b.Property<float>("penaltyVeggieVegan")
                        .HasColumnType("float");

                    b.Property<int>("resPiecesMeat")
                        .HasColumnType("int");

                    b.Property<int>("resPiecesVegan")
                        .HasColumnType("int");

                    b.Property<int>("resPiecesVegetarian")
                        .HasColumnType("int");

                    b.Property<float>("totalCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
